---
- name: Install Java
  hosts: app_server
  become: yes
  become_user: root
  roles:
    - geerlingguy.java

- name: Download Application from Repo
  hosts: app_server
  tasks:
    - debug: msg="{{ lookup('env','ARTIFACT_URL') }}"
    - get_url:
        url: '{{ env.ARTIFACT_URL }}'
        dest: '/tmp/{{ env.APP_NAME }}'

- name: Setup Spring Boot
  hosts: app_server
  become: yes
  become_user: root

  roles: 
    - { role: pellepelster.springboot-role,
        spring_boot_file_source_local: '/tmp/{{ APP_NAME }}'
    } 