---
- name: Install Java
  hosts: "{{ lookup('env','APP_HOST_GROUP') }}"
  become: yes
  become_user: root
  roles:
    - geerlingguy.java

- name: Download Application from Repo
  hosts: "{{ lookup('env','APP_HOST_GROUP') }}"
  tasks:
    - get_url:
        force: yes
        # url: "{{ ARTIFACT_URL }}"
        # dest: '/tmp/{{ APP_NAME }}.jar'
        url: "{{ lookup('env','ARTIFACT_URL') }}"
        dest: "/tmp/{{ lookup('env','APP_NAME') }}.jar"
    - stat: 
        # path: '/tmp/{{ APP_NAME }}.jar'
        path: "/tmp/{{ lookup('env','APP_NAME') }}.jar"

- name: Setup Spring Boot
  hosts: "{{ lookup('env','APP_HOST_GROUP') }}"
  become: yes
  become_user: root
  roles: 
    - { role: pellepelster.springboot-role,
        spring_boot_file: "{{ lookup('env','APP_NAME') }}.jar",
        # spring_boot_file: "{{ APP_NAME }}.jar",
        spring_boot_file_source: "/tmp/{{ lookup('env','APP_NAME') }}.jar",
        spring_boot_application_id: "{{ lookup('env','APP_NAME') }}"
        # spring_boot_file_source: "/tmp/{{ APP_NAME }}.jar",
        # spring_boot_application_id: '{{ APP_NAME }}'
    } 